from datetime import time


# Listing
LISTING_SOFT_DELETE_DAYS = 180
LISTING_MAX_PHOTOS = 10


# Booking
BOOKING_MAX_DAYS_AHEAD = 365
BOOKING_CANCELLATION_DEADLINE_HOURS = 24

BOOKING_CHECK_IN_START = time(14, 0)
BOOKING_CHECK_IN_END = time(22, 0)

BOOKING_CHECK_OUT_START = time(7, 0)
BOOKING_CHECK_OUT_END = time(11, 0)

