# Generated by Django 6.1.1 on 2026-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['position', 'created_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='photo_listing_created_idx',
        ),
        migrations.AddField(
            model_name='photo',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['listing', 'position'], name='photo_listing_position_idx'),
        ),
    ]
