# Generated by Django 6.1.1 on 2026-09-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='listings/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Position'),
        ),
    ]
