# Generated by Django 6.1.1 on 2026-09-13 10:10

import core.validators
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_photo_image_alter_photo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='price_per_night',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, validators=[core.validators.validate_positive_price], verbose_name='Price per night'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, validators=[core.validators.validate_positive_price], verbose_name='Price per night'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='listings/', verbose_name='Image'),
        ),
    ]
