# Generated by Django 6.1.1 on 2026-09-10 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='snapshot_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Tenant email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='snapshot_first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Tenant first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='snapshot_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Tenant last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='snapshot_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Tenant email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='snapshot_first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Tenant first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='snapshot_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Tenant last name'),
            preserve_default=False,
        ),
    ]
