# Generated by Django 6.1.1 on 2026-09-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='review_comment_at_idx',
        ),
    ]
